services:
  # Backend
  - type: web
    name: link-shortener-backend
    env: docker
    repo: https://github.com/marco-villanueva/link-shortener-mvp.git
    rootDir: backend
    plan: free
    dockerfilePath: Dockerfile

    preDeployCommand: "npx prisma migrate deploy"

    envVars:
      - key: DATABASE_URL
        value: "file:/data/production.db"
      - key: FRONTEND_URL
        fromService:
          type: web
          name: link-shortener-frontend
          property: url

    disks:
      - name: sqlite-data
        mountPath: /data
        sizeGB: 1

  # Frontend
  - type: web
    name: link-shortener-frontend
    env: docker
    repo: https://github.com/marco-villanueva/link-shortener-mvp.git
    rootDir: frontend
    plan: free
    dockerfilePath: Dockerfile
